### ISSUE TITLE
API - Search Roles + Location Filter

### ISSUE THREAD

**Issue by victoriatran17** [BobaTalks/internship-tracker#35]
I want to be able find SWE and design roles based on a certain location. I want them to also be able to filter by company, education level, location/remote, experience, internship season (semester or quarter) and date posted

https://www.figma.com/file/KFMxlfGvnZncpyvACICstf/JMT-Figma?node-id=1585-43535&t=4p5IJpm5fyXlmgy6-0

![Image](https://user-images.githubusercontent.com/118402811/232127495-4e1123fa-1d9d-42c0-b635-089ffbc9a778.jpeg)

**Comment by jwu910** [comment]
I believe the server side requests should include the text search, and location as the default search criteria according to the home page and search bar at the top.

Filtering we could look at filtering client side after results have been returned.

If we wanted to, we could also include the API call here after users want to search further, but we should distinguish the difference between "search" and "filter" becuase they are inherently different and the expectations of the experience are different

**Comment by jwu910** [comment]
Need to add an estimate to this @kpxwinter @a-camarillo

**Comment by JennaXiao3** [comment]
@jwu910 should this be a frontend task since filtering is handled in the frontend (from what i understand)?

**Comment by jwu910** [comment]
The `search` side should be server side. I believe keyword matching as well as location should be driven by backend queries. The initial user input for those would otherwise return _all_ internships if we did not include that.

I can see someone having to type in Toronto or California every time, or if we're preserving existing `filters`, then the server is going to be sending over unnecessary data when the user doesn't care at all. I dont expect that this will get so large that client side `filtering` will start to take a performance hit, but we also have `pagination` as future work that will help mitigate some of that.

I think this ticket should cover server side `search` still cause we're already filtering on the client side with the work you did adding the filters. We just need to make sure the api endpoints for the search get hit when keywords or location is supplied/changed/etc
